# Generated by Django 6.0.7 on 2026-07-24 18:17

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloning", "Cloning"),
                            ("chunking", "Chunking"),
                            ("embedding", "Embedding"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("temperature", models.FloatField(default=0.2)),
                ("top_p", models.FloatField(default=0.9)),
                ("top_k", models.IntegerField(default=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="search.repo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1000)),
                (
                    "symbol_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "symbol_type",
                    models.CharField(
                        choices=[
                            ("function", "Function"),
                            ("class", "Class"),
                            ("method", "Method"),
                            ("module", "Module"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_line", models.IntegerField()),
                ("end_line", models.IntegerField()),
                ("source_code", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calls",
                    models.ManyToManyField(
                        blank=True, related_name="called_by", to="search.codechunk"
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="search.repo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["repo", "file_path"],
                        name="search_code_repo_id_e388ff_idx",
                    )
                ],
            },
        ),
    ]
